import localFont from 'next/font/local';
import { headers } from 'next/headers';

import { config } from '~/lib/viem';

import { cookieToInitialState } from 'wagmi';
import { Web3Provider } from '~/providers';
import '~/styles/globals.css';

const chaletFont = localFont({
  src: '../../public/fonts/chalet.ttf',
  variable: '--font-sans',
});

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));

  return (
    <html lang='en'>
      <Web3Provider initialState={initialState}>
        <body className={`font-sans ${chaletFont.variable}`}>{children}</body>
      </Web3Provider>
    </html>
  );
}
